compute and store the limit violations after the loadflow
gridsuite/loadflow-server pull request #67
Opened 2023-10-05 13:12 UTC by FranckLecuyer

2023-10-09 09:28 UTC, antoinebhs approved these changes
Code OK
Tests OK

2023-10-09 12:30 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/loadflow/server/entities/LimitViolationEmbeddable.java
> +    private String limitName;
added

2023-10-16 18:17 UTC, dbraquart requested changes
code: change request for a suggestion
tests: ok

2023-10-17 08:43 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/loadflow/server/service/LoadFlowWorkerService.java
> +            limitReduction = 0.001F;  // 0 is not allowed
Done

2023-10-17 08:43 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/loadflow/server/LoadFlowController.java
> +                                    @Parameter(description = "The limit reduction") @RequestParam(name = "limitReduction", required = false) Float limitReduction,
Done

2023-10-17 12:01 UTC, dbraquart approved these changes
code: ok
tests: not done with last commit

2023-10-17 12:54 UTC, merged